test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: GCS
  project: cloud-skill
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: <%= ENV['BUCKET_ID'] %>

google_prod:
  service: GCS
  project: cloud-skill
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: <%= ENV['BUCKET_ID'] %>
